/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace HalalRegistry {
  export type CertificateStruct = {
    certificateId: BytesLike;
    productId: BytesLike;
    issuingBody: string;
    issuedAt: BigNumberish;
    expiresAt: BigNumberish;
    isValid: boolean;
  };

  export type CertificateStructOutput = [
    certificateId: string,
    productId: string,
    issuingBody: string,
    issuedAt: bigint,
    expiresAt: bigint,
    isValid: boolean
  ] & {
    certificateId: string;
    productId: string;
    issuingBody: string;
    issuedAt: bigint;
    expiresAt: bigint;
    isValid: boolean;
  };

  export type ProductStruct = {
    productId: BytesLike;
    name: string;
    registeredBy: AddressLike;
    registeredAt: BigNumberish;
    isHalalCertified: boolean;
    certificateId: BytesLike;
    exists: boolean;
  };

  export type ProductStructOutput = [
    productId: string,
    name: string,
    registeredBy: string,
    registeredAt: bigint,
    isHalalCertified: boolean,
    certificateId: string,
    exists: boolean
  ] & {
    productId: string;
    name: string;
    registeredBy: string;
    registeredAt: bigint;
    isHalalCertified: boolean;
    certificateId: string;
    exists: boolean;
  };
}

export interface HalalRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificates"
      | "getAllProductIds"
      | "getCertificate"
      | "getProduct"
      | "getProductCount"
      | "isHalalCertified"
      | "issueCertificate"
      | "products"
      | "registerProduct"
      | "revokeCertificate"
      | "roleManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRevoked"
      | "ProductRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "certificates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProductIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isHalalCertified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [BytesLike, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "products", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProductIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isHalalCertified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    productId: BytesLike,
    certificateId: BytesLike,
    issuingBody: string,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    certificateId: string,
    issuingBody: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    productId: string;
    certificateId: string;
    issuingBody: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [
    certificateId: BytesLike,
    productId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    certificateId: string,
    productId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    certificateId: string;
    productId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [
    productId: BytesLike,
    manufacturer: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    manufacturer: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: string;
    manufacturer: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HalalRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HalalRegistry;
  waitForDeployment(): Promise<this>;

  interface: HalalRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        certificateId: string;
        productId: string;
        issuingBody: string;
        issuedAt: bigint;
        expiresAt: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getAllProductIds: TypedContractMethod<[], [string[]], "view">;

  getCertificate: TypedContractMethod<
    [certificateId: BytesLike],
    [HalalRegistry.CertificateStructOutput],
    "view"
  >;

  getProduct: TypedContractMethod<
    [productId: BytesLike],
    [HalalRegistry.ProductStructOutput],
    "view"
  >;

  getProductCount: TypedContractMethod<[], [bigint], "view">;

  isHalalCertified: TypedContractMethod<
    [productId: BytesLike],
    [boolean],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [
      productId: BytesLike,
      certificateId: BytesLike,
      issuingBody: string,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  products: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, string, boolean] & {
        productId: string;
        name: string;
        registeredBy: string;
        registeredAt: bigint;
        isHalalCertified: boolean;
        certificateId: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [productId: BytesLike, name: string],
    [void],
    "nonpayable"
  >;

  revokeCertificate: TypedContractMethod<
    [certificateId: BytesLike],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        certificateId: string;
        productId: string;
        issuingBody: string;
        issuedAt: bigint;
        expiresAt: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProductIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [certificateId: BytesLike],
    [HalalRegistry.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [productId: BytesLike],
    [HalalRegistry.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isHalalCertified"
  ): TypedContractMethod<[productId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      productId: BytesLike,
      certificateId: BytesLike,
      issuingBody: string,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, string, boolean] & {
        productId: string;
        name: string;
        registeredBy: string;
        registeredAt: bigint;
        isHalalCertified: boolean;
        certificateId: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<
    [productId: BytesLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<[certificateId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(bytes32,bytes32,string,uint256)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(bytes32,bytes32,uint256)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "ProductRegistered(bytes32,address,string,uint256)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
  };
}
