/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChainTracker {
  export type ChainEventStruct = {
    eventId: BytesLike;
    productId: BytesLike;
    eventType: BigNumberish;
    actor: AddressLike;
    timestamp: BigNumberish;
    location: string;
    notes: string;
  };

  export type ChainEventStructOutput = [
    eventId: string,
    productId: string,
    eventType: bigint,
    actor: string,
    timestamp: bigint,
    location: string,
    notes: string
  ] & {
    eventId: string;
    productId: string;
    eventType: bigint;
    actor: string;
    timestamp: bigint;
    location: string;
    notes: string;
  };
}

export interface SupplyChainTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEvent"
      | "getEventCount"
      | "getProductHistory"
      | "recordEvent"
      | "roleManager"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SupplyChainEventRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordEvent",
    values: [BytesLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
}

export namespace SupplyChainEventRecordedEvent {
  export type InputTuple = [
    productId: BytesLike,
    eventId: BytesLike,
    eventType: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    location: string,
    notes: string
  ];
  export type OutputTuple = [
    productId: string,
    eventId: string,
    eventType: bigint,
    actor: string,
    timestamp: bigint,
    location: string,
    notes: string
  ];
  export interface OutputObject {
    productId: string;
    eventId: string;
    eventType: bigint;
    actor: string;
    timestamp: bigint;
    location: string;
    notes: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChainTracker extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChainTracker;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEvent: TypedContractMethod<
    [productId: BytesLike, index: BigNumberish],
    [SupplyChainTracker.ChainEventStructOutput],
    "view"
  >;

  getEventCount: TypedContractMethod<[productId: BytesLike], [bigint], "view">;

  getProductHistory: TypedContractMethod<
    [productId: BytesLike],
    [SupplyChainTracker.ChainEventStructOutput[]],
    "view"
  >;

  recordEvent: TypedContractMethod<
    [
      productId: BytesLike,
      eventType: BigNumberish,
      location: string,
      notes: string
    ],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [productId: BytesLike, index: BigNumberish],
    [SupplyChainTracker.ChainEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEventCount"
  ): TypedContractMethod<[productId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProductHistory"
  ): TypedContractMethod<
    [productId: BytesLike],
    [SupplyChainTracker.ChainEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordEvent"
  ): TypedContractMethod<
    [
      productId: BytesLike,
      eventType: BigNumberish,
      location: string,
      notes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "SupplyChainEventRecorded"
  ): TypedContractEvent<
    SupplyChainEventRecordedEvent.InputTuple,
    SupplyChainEventRecordedEvent.OutputTuple,
    SupplyChainEventRecordedEvent.OutputObject
  >;

  filters: {
    "SupplyChainEventRecorded(bytes32,bytes32,uint8,address,uint256,string,string)": TypedContractEvent<
      SupplyChainEventRecordedEvent.InputTuple,
      SupplyChainEventRecordedEvent.OutputTuple,
      SupplyChainEventRecordedEvent.OutputObject
    >;
    SupplyChainEventRecorded: TypedContractEvent<
      SupplyChainEventRecordedEvent.InputTuple,
      SupplyChainEventRecordedEvent.OutputTuple,
      SupplyChainEventRecordedEvent.OutputObject
    >;
  };
}
